-- megafunction wizard: %ALTIOBUF%
-- GENERATION: STANDARD
-- VERSION: WM1.0
-- MODULE: altiobuf_out 

-- ============================================================
-- File Name: altio_out.vhd
-- Megafunction Name(s):
-- 			altiobuf_out
--
-- Simulation Library Files(s):
-- 			
-- ============================================================
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
--
-- 16.1.1 Build 200 11/30/2016 SJ Lite Edition
-- ************************************************************


--Copyright (C) 2016  Intel Corporation. All rights reserved.
--Your use of Intel Corporation's design tools, logic functions 
--and other software and tools, and its AMPP partner logic 
--functions, and any output files from any of the foregoing 
--(including device programming or simulation files), and any 
--associated documentation or information are expressly subject 
--to the terms and conditions of the Intel Program License 
--Subscription Agreement, the Intel Quartus Prime License Agreement,
--the Intel MegaCore Function License Agreement, or other 
--applicable license agreement, including, without limitation, 
--that your use is for the sole purpose of programming logic 
--devices manufactured by Intel and sold by Intel or its 
--authorized distributors.  Please refer to the applicable 
--agreement for further details.


--altiobuf_out CBX_AUTO_BLACKBOX="ALL" DEVICE_FAMILY="Cyclone V" ENABLE_BUS_HOLD="FALSE" LEFT_SHIFT_SERIES_TERMINATION_CONTROL="FALSE" NUMBER_OF_CHANNELS=13 OPEN_DRAIN_OUTPUT="FALSE" PSEUDO_DIFFERENTIAL_MODE="FALSE" USE_DIFFERENTIAL_MODE="FALSE" USE_OE="TRUE" USE_TERMINATION_CONTROL="FALSE" datain dataout oe
--VERSION_BEGIN 16.1 cbx_altiobuf_out 2016:11:30:18:10:07:SJ cbx_mgl 2016:11:30:18:11:28:SJ cbx_stratixiii 2016:11:30:18:10:07:SJ cbx_stratixv 2016:11:30:18:10:07:SJ  VERSION_END

 LIBRARY cyclonev;
 USE cyclonev.all;

--synthesis_resources = cyclonev_io_obuf 13 
 LIBRARY ieee;
 USE ieee.std_logic_1164.all;

 ENTITY  altio_out_iobuf_out_ivs IS 
	 PORT 
	 ( 
		 datain	:	IN  STD_LOGIC_VECTOR (12 DOWNTO 0);
		 dataout	:	OUT  STD_LOGIC_VECTOR (12 DOWNTO 0);
		 oe	:	IN  STD_LOGIC_VECTOR (12 DOWNTO 0) := (OTHERS => '1')
	 ); 
 END altio_out_iobuf_out_ivs;

 ARCHITECTURE RTL OF altio_out_iobuf_out_ivs IS

	 SIGNAL  wire_obufa_i	:	STD_LOGIC_VECTOR (12 DOWNTO 0);
	 SIGNAL  wire_obufa_o	:	STD_LOGIC_VECTOR (12 DOWNTO 0);
	 SIGNAL  wire_obufa_oe	:	STD_LOGIC_VECTOR (12 DOWNTO 0);
	 SIGNAL  oe_w :	STD_LOGIC_VECTOR (12 DOWNTO 0);
	 COMPONENT  cyclonev_io_obuf
	 GENERIC 
	 (
		bus_hold	:	STRING := "false";
		open_drain_output	:	STRING := "false";
		shift_series_termination_control	:	STRING := "false";
		lpm_type	:	STRING := "cyclonev_io_obuf"
	 );
	 PORT
	 ( 
		dynamicterminationcontrol	:	IN STD_LOGIC := '0';
		i	:	IN STD_LOGIC := '0';
		o	:	OUT STD_LOGIC;
		obar	:	OUT STD_LOGIC;
		oe	:	IN STD_LOGIC := '1';
		parallelterminationcontrol	:	IN STD_LOGIC_VECTOR(15 DOWNTO 0) := (OTHERS => '0');
		seriesterminationcontrol	:	IN STD_LOGIC_VECTOR(15 DOWNTO 0) := (OTHERS => '0')
	 ); 
	 END COMPONENT;
 BEGIN

	dataout <= wire_obufa_o;
	oe_w <= oe;
	wire_obufa_i <= datain;
	wire_obufa_oe <= oe_w;
	loop0 : FOR i IN 0 TO 12 GENERATE 
	  obufa :  cyclonev_io_obuf
	  GENERIC MAP (
		bus_hold => "false",
		open_drain_output => "false"
	  )
	  PORT MAP ( 
		i => wire_obufa_i(i),
		o => wire_obufa_o(i),
		oe => wire_obufa_oe(i)
	  );
	END GENERATE loop0;

 END RTL; --altio_out_iobuf_out_ivs
--VALID FILE


LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY altio_out IS
	PORT
	(
		datain		: IN STD_LOGIC_VECTOR (12 DOWNTO 0);
		oe		: IN STD_LOGIC_VECTOR (12 DOWNTO 0);
		dataout		: OUT STD_LOGIC_VECTOR (12 DOWNTO 0)
	);
END altio_out;


ARCHITECTURE RTL OF altio_out IS

	SIGNAL sub_wire0	: STD_LOGIC_VECTOR (12 DOWNTO 0);



	COMPONENT altio_out_iobuf_out_ivs
	PORT (
			datain	: IN STD_LOGIC_VECTOR (12 DOWNTO 0);
			oe	: IN STD_LOGIC_VECTOR (12 DOWNTO 0);
			dataout	: OUT STD_LOGIC_VECTOR (12 DOWNTO 0)
	);
	END COMPONENT;

BEGIN
	dataout    <= sub_wire0(12 DOWNTO 0);

	altio_out_iobuf_out_ivs_component : altio_out_iobuf_out_ivs
	PORT MAP (
		datain => datain,
		oe => oe,
		dataout => sub_wire0
	);



END RTL;

-- ============================================================
-- CNX file retrieval info
-- ============================================================
-- Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
-- Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
-- Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
-- Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone V"
-- Retrieval info: CONSTANT: enable_bus_hold STRING "FALSE"
-- Retrieval info: CONSTANT: left_shift_series_termination_control STRING "FALSE"
-- Retrieval info: CONSTANT: number_of_channels NUMERIC "13"
-- Retrieval info: CONSTANT: open_drain_output STRING "FALSE"
-- Retrieval info: CONSTANT: pseudo_differential_mode STRING "FALSE"
-- Retrieval info: CONSTANT: use_differential_mode STRING "FALSE"
-- Retrieval info: CONSTANT: use_oe STRING "TRUE"
-- Retrieval info: CONSTANT: use_termination_control STRING "FALSE"
-- Retrieval info: USED_PORT: datain 0 0 13 0 INPUT NODEFVAL "datain[12..0]"
-- Retrieval info: USED_PORT: dataout 0 0 13 0 OUTPUT NODEFVAL "dataout[12..0]"
-- Retrieval info: USED_PORT: oe 0 0 13 0 INPUT NODEFVAL "oe[12..0]"
-- Retrieval info: CONNECT: @datain 0 0 13 0 datain 0 0 13 0
-- Retrieval info: CONNECT: @oe 0 0 13 0 oe 0 0 13 0
-- Retrieval info: CONNECT: dataout 0 0 13 0 @dataout 0 0 13 0
-- Retrieval info: GEN_FILE: TYPE_NORMAL altio_out.vhd TRUE
-- Retrieval info: GEN_FILE: TYPE_NORMAL altio_out.inc FALSE
-- Retrieval info: GEN_FILE: TYPE_NORMAL altio_out.cmp TRUE
-- Retrieval info: GEN_FILE: TYPE_NORMAL altio_out.bsf TRUE
-- Retrieval info: GEN_FILE: TYPE_NORMAL altio_out_inst.vhd FALSE
