# TCL File Generated by Component Editor 16.1
# Thu Mar 15 15:02:05 EET 2018
# DO NOT MODIFY


# 
# Avalon_MM_external "Avalon_MM_external" v1.0
# Lime Microsystems 2018.03.15.15:02:05
# Component to export Avalon master bus from QSYS system
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Avalon_MM_external
# 
set_module_property DESCRIPTION "Component to export Avalon master bus from QSYS system"
set_module_property NAME Avalon_MM_external
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Lime Microsystems"
set_module_property DISPLAY_NAME Avalon_MM_external
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Avalon_MM_external
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file Avalon_MM_external.vhd VHDL PATH src/Avalon_MM_external/Avalon_MM_external.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avs_s0
# 
add_interface avs_s0 avalon end
set_interface_property avs_s0 addressUnits WORDS
set_interface_property avs_s0 associatedClock clock
set_interface_property avs_s0 associatedReset reset
set_interface_property avs_s0 bitsPerSymbol 8
set_interface_property avs_s0 bridgedAddressOffset 0
set_interface_property avs_s0 burstOnBurstBoundariesOnly false
set_interface_property avs_s0 burstcountUnits WORDS
set_interface_property avs_s0 explicitAddressSpan 0
set_interface_property avs_s0 holdTime 0
set_interface_property avs_s0 linewrapBursts false
set_interface_property avs_s0 maximumPendingReadTransactions 1
set_interface_property avs_s0 maximumPendingWriteTransactions 0
set_interface_property avs_s0 readLatency 0
set_interface_property avs_s0 readWaitTime 1
set_interface_property avs_s0 setupTime 0
set_interface_property avs_s0 timingUnits Cycles
set_interface_property avs_s0 writeWaitTime 0
set_interface_property avs_s0 ENABLED true
set_interface_property avs_s0 EXPORT_OF ""
set_interface_property avs_s0 PORT_NAME_MAP ""
set_interface_property avs_s0 CMSIS_SVD_VARIABLES ""
set_interface_property avs_s0 SVD_ADDRESS_GROUP ""

add_interface_port avs_s0 avs_s0_address address Input 8
add_interface_port avs_s0 avs_s0_read read Input 1
add_interface_port avs_s0 avs_s0_readdata readdata Output 8
add_interface_port avs_s0 avs_s0_write write Input 1
add_interface_port avs_s0 avs_s0_writedata writedata Input 8
add_interface_port avs_s0 avs_s0_waitrequest waitrequest Output 1
add_interface_port avs_s0 avs_s0_readdatavalid readdatavalid Output 1
set_interface_assignment avs_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment avs_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point avm_m0
# 
add_interface avm_m0 avalon start
set_interface_property avm_m0 addressUnits SYMBOLS
set_interface_property avm_m0 associatedClock clock
set_interface_property avm_m0 associatedReset reset
set_interface_property avm_m0 bitsPerSymbol 8
set_interface_property avm_m0 burstOnBurstBoundariesOnly false
set_interface_property avm_m0 burstcountUnits WORDS
set_interface_property avm_m0 doStreamReads false
set_interface_property avm_m0 doStreamWrites false
set_interface_property avm_m0 holdTime 0
set_interface_property avm_m0 linewrapBursts false
set_interface_property avm_m0 maximumPendingReadTransactions 1
set_interface_property avm_m0 maximumPendingWriteTransactions 0
set_interface_property avm_m0 readLatency 0
set_interface_property avm_m0 readWaitTime 1
set_interface_property avm_m0 setupTime 0
set_interface_property avm_m0 timingUnits Cycles
set_interface_property avm_m0 writeWaitTime 0
set_interface_property avm_m0 ENABLED true
set_interface_property avm_m0 EXPORT_OF ""
set_interface_property avm_m0 PORT_NAME_MAP ""
set_interface_property avm_m0 CMSIS_SVD_VARIABLES ""
set_interface_property avm_m0 SVD_ADDRESS_GROUP ""

add_interface_port avm_m0 avm_m0_address address Output 8
add_interface_port avm_m0 avm_m0_read read Output 1
add_interface_port avm_m0 avm_m0_waitrequest waitrequest Input 1
add_interface_port avm_m0 avm_m0_readdata readdata Input 8
add_interface_port avm_m0 avm_m0_write write Output 1
add_interface_port avm_m0 avm_m0_writedata writedata Output 8
add_interface_port avm_m0 avm_m0_readdatavalid readdatavalid Input 1


# 
# connection point clock_source
# 
add_interface clock_source clock start
set_interface_property clock_source associatedDirectClock ""
set_interface_property clock_source clockRate 0
set_interface_property clock_source clockRateKnown false
set_interface_property clock_source ENABLED true
set_interface_property clock_source EXPORT_OF ""
set_interface_property clock_source PORT_NAME_MAP ""
set_interface_property clock_source CMSIS_SVD_VARIABLES ""
set_interface_property clock_source SVD_ADDRESS_GROUP ""

add_interface_port clock_source clock_source_clk clk Output 1


# 
# connection point reset_source
# 
add_interface reset_source reset start
set_interface_property reset_source associatedClock clock
set_interface_property reset_source associatedDirectReset ""
set_interface_property reset_source associatedResetSinks reset
set_interface_property reset_source synchronousEdges DEASSERT
set_interface_property reset_source ENABLED true
set_interface_property reset_source EXPORT_OF ""
set_interface_property reset_source PORT_NAME_MAP ""
set_interface_property reset_source CMSIS_SVD_VARIABLES ""
set_interface_property reset_source SVD_ADDRESS_GROUP ""

add_interface_port reset_source reset_source_reset reset Output 1

